/*Exercicio 1*/
SELECT * FROM CLIENTES

/*Exercicio 2*/
SELECT * FROM FILME

/*Exercicio 3*/
SELECT * FROM CATEGORIA

/*Exercicio 4*/
SELECT * FROM Clientes WHERE Sexo = 'M' AND Cidade = 'Sorocaba' 

/*Exercicio 5*/
SELECT Nome, Telefone FROM CLIENTES ORDER BY Nome;

/*Exercicio 6*/
SELECT COUNT (*) FROM Clientes WHERE Sexo = 'F'

/*Exercicio 7*/
SELECT * FROM Categoria ORDER BY Nome_Categoria ASC;

/*Exercicio 8*/
SELECT * FROM Filme WHERE Diretor = 'Shawn Levy' AND Reservada = 'n';

/*Exercicio 9*/
SELECT * FROM Filme WHERE Valor_Locacao > 5 AND Reservada = 'S';

/*Exercicio 10*/
SELECT DISTINCT Diretor FROM Filme;

/*Exercicio 11*/
SELECT COUNT(*) FROM FILME WHERE Reservada = 'S'; 

/*Exercicio 12*/
SELECT MAX(Valor_Locacao) FROM Filme;

/*Exercicio 13*/
SELECT * FROM FILME WHERE COD_CATEGORIA IN (SELECT COD_CATEGORIA FROM CATEGORIA WHERE NOME_CATEGORIA = 'Ação');

/*Exercicio 14 */
SELECT *, cat.COD_CATEGORIA FROM FILME f LEFT OUTER JOIN CATEGORIA cat ON cat.COD_CATEGORIA = f.COD_CATEGORIA
WHERE (cat.NOME_CATEGORIA = 'Romance' OR cat.NOME_CATEGORIA = 'Aventura') AND f.RESERVADA = 's' AND VALOR_LOCACAO < 5;

/*Exercicio 15 */
SELECT f.FILME, c.NOME FROM CLIENTES c FULL JOIN LOCACOES l ON l.COD_CLIENTE = c.COD_CLIENTE
FULL JOIN FILME f ON f.COD_FILME = l.COD_FILME WHERE c.NOME = 'Renata Cristina';

/*Exercicio 16 */
SELECT c.COD_CLIENTE, c.NOME, COUNT(l.COD_LOCACAO) AS LocacoesTotal FROM CLIENTES c
FULL JOIN LOCACOES l ON l.COD_CLIENTE = c.COD_CLIENTE GROUP BY c.COD_CLIENTE, c.NOME HAVING COUNT(l.COD_LOCACAO) > 3

/*Exercicio 17 */
SELECT c.NOME, SUM(all f.VALOR_LOCACAO) AS GastoTotal FROM CLIENTES c
FULL JOIN LOCACOES l ON l.COD_CLIENTE = c.COD_CLIENTE 
FULL JOIN FILME f ON f.COD_FILME = l.COD_FILME WHERE c.NOME = 'Renata Cristina' GROUP BY c.NOME;

/*Exercicio 18 */
SELECT ROUND(avg(VALOR_LOCACAO), 2) AS MEDIADELOCACAO FROM FILME;

/*Exercicio 19 */
SELECT MIN(VALOR_LOCACAO) AS MIN_LOCACAO FROM FILME;

/*Exercicio 20 */
SELECT C.NOME_CATEGORIA, COUNT(F.COD_FILME) AS Quantidade_Filmes
FROM FILME F
JOIN CATEGORIA C ON F.COD_CATEGORIA = C.COD_CATEGORIA
GROUP BY C.NOME_CATEGORIA;


