/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.JOptionPane;

/**
 *
 * @author Alunos
 */
public class cal extends javax.swing.JFrame {

    /**
     * Creates new form cal
     */
    public cal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtbNumero1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtbNumero2 = new javax.swing.JTextField();
        btoSoma = new javax.swing.JButton();
        btoSubtracao = new javax.swing.JButton();
        btoMultiplicacao = new javax.swing.JButton();
        btoDivisao = new javax.swing.JButton();
        txtboxResultado = new javax.swing.JTextField();
        btoResultado = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtbNumero3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtbNumero4 = new javax.swing.JTextField();
        btoSoma1 = new javax.swing.JButton();
        btoSubtracao1 = new javax.swing.JButton();
        btoMultiplicacao1 = new javax.swing.JButton();
        btoDivisao1 = new javax.swing.JButton();
        txtboxResultado1 = new javax.swing.JTextField();
        btoResultado1 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(74, 74, 225));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel1.setText("Número 1");

        txtbNumero1.setText("jTextField1");
        txtbNumero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbNumero1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel2.setText("Número 2");

        txtbNumero2.setText("jTextField1");

        btoSoma.setText("+");
        btoSoma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btoSomaMouseClicked(evt);
            }
        });

        btoSubtracao.setText("-");

        btoMultiplicacao.setText("x");

        btoDivisao.setText("/");
        btoDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoDivisaoActionPerformed(evt);
            }
        });

        txtboxResultado.setText("jTextField3");

        btoResultado.setBackground(new java.awt.Color(204, 204, 255));
        btoResultado.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btoResultado.setText("Resultado");
        btoResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoResultadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(29, 29, 29)
                            .addComponent(txtbNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtbNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btoSoma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btoSubtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btoMultiplicacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(18, 18, 18)
                            .addComponent(btoDivisao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(18, 18, 18)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtboxResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btoResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtbNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btoSoma)
                    .addComponent(btoSubtracao)
                    .addComponent(btoMultiplicacao)
                    .addComponent(btoDivisao))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtboxResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btoResultado))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(74, 74, 225));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel3.setText("Número 1");

        txtbNumero3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbNumero3ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel4.setText("Número 2");

        btoSoma1.setText("+");
        btoSoma1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btoSoma1MouseClicked(evt);
            }
        });
        btoSoma1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoSoma1ActionPerformed(evt);
            }
        });

        btoSubtracao1.setText("-");

        btoMultiplicacao1.setText("x");

        btoDivisao1.setText("/");
        btoDivisao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoDivisao1ActionPerformed(evt);
            }
        });

        txtboxResultado1.setText("jTextField3");

        btoResultado1.setBackground(new java.awt.Color(204, 204, 255));
        btoResultado1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btoResultado1.setText("Resultado");
        btoResultado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoResultado1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(29, 29, 29)
                            .addComponent(txtbNumero3, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtbNumero4, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(btoSoma1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btoSubtracao1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btoMultiplicacao1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(18, 18, 18)
                            .addComponent(btoDivisao1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(18, 18, 18)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtboxResultado1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btoResultado1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 62, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtbNumero3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbNumero4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btoSoma1)
                    .addComponent(btoSubtracao1)
                    .addComponent(btoMultiplicacao1)
                    .addComponent(btoDivisao1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtboxResultado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btoResultado1))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtbNumero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbNumero1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbNumero1ActionPerformed

    private void btoSomaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btoSomaMouseClicked
        System.out.println("Eu quero somar");
    }//GEN-LAST:event_btoSomaMouseClicked

    private void btoDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoDivisaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btoDivisaoActionPerformed

    private void btoResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btoResultadoActionPerformed

    private void txtbNumero3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbNumero3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbNumero3ActionPerformed

    private void btoSoma1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btoSoma1MouseClicked
        
        if (txtbNumero3.getText().isBlank())
            txtbNumero3.setText(JOptionPane.showInputDialog("Digite um valor numerico: "));
       
        /*O nome após o double pode alterar, contudo o que esta dentro do parenteses,
        deve ser igual a variavel que foi atribuida*/
        /*Para somar*/
        double numero1 = Double.parseDouble(txtbNumero3.getText());
        double numero2 = Double.parseDouble(txtbNumero4.getText());
        txtboxResultado1.setText(Double.toString(Calcular.somar(numero1,numero2)));
        
        /*Para subtrair*/
        double numero3 = Double.parseDouble(txtbNumero3.getText());
        double numero4 = Double.parseDouble(txtbNumero4.getText());
        txtboxResultado1.setText(Double.toString(Calcular.subtrair(numero3,numero4)));
        
        
        
        
        
        /*System.out.println("Eu quero somar! " + numero3);
        /*Jop chama a telinha, rootpane exibe o que quer que escreva*/
        /*int resp = JOptionPane.showConfirmDialog(rootPane, "Vamos somar?");
        String segundoValor="....";*/
        /*if (resp == JOptionPane.YES_OPTION);
               segundoValor=JOptionPane.showInputDialog(rootPane,"Digite o segundo valor?");
        JOptionPane.showConfirmDialog(rootPane, segundoValor);*/
               
    }//GEN-LAST:event_btoSoma1MouseClicked

    private void btoDivisao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoDivisao1ActionPerformed
        // TODO add your handling code here:
        /*Para dividir*/
        double numero7 = Double.parseDouble(txtbNumero3.getText());
        double numero8 = Double.parseDouble(txtbNumero4.getText()); 
        txtboxResultado1.setText(Double.toString(Calcular.dividir(numero7,numero8)));
    }//GEN-LAST:event_btoDivisao1ActionPerformed

    private void btoResultado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoResultado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btoResultado1ActionPerformed

    private void btoSoma1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoSoma1ActionPerformed
        // TODO add your handling code here:
        double numero1 = Double.parseDouble(txtbNumero3.getText());
        double numero2 = Double.parseDouble(txtbNumero4.getText());
        txtboxResultado1.setText(Double.toString(Calcular.somar(numero1,numero2)));
    }//GEN-LAST:event_btoSoma1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btoDivisao;
    private javax.swing.JButton btoDivisao1;
    private javax.swing.JButton btoMultiplicacao;
    private javax.swing.JButton btoMultiplicacao1;
    private javax.swing.JButton btoResultado;
    private javax.swing.JButton btoResultado1;
    private javax.swing.JButton btoSoma;
    private javax.swing.JButton btoSoma1;
    private javax.swing.JButton btoSubtracao;
    private javax.swing.JButton btoSubtracao1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtbNumero1;
    private javax.swing.JTextField txtbNumero2;
    private javax.swing.JTextField txtbNumero3;
    private javax.swing.JTextField txtbNumero4;
    private javax.swing.JTextField txtboxResultado;
    private javax.swing.JTextField txtboxResultado1;
    // End of variables declaration//GEN-END:variables
}
